# Generated by Django 2.1.7 on 2019-03-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.IntegerField(verbose_name='Ficha')),
                ('classificacao', models.CharField(choices=[('AZ', 'Azul'), ('VD', 'Verde'), ('AM', 'Amarelo'), ('VM', 'Vermelho')], max_length=2, verbose_name='Classificação')),
                ('senha', models.IntegerField(blank=True, null=True, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('termino', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('primeiro', models.BooleanField(verbose_name='Primeiro Atendimento')),
                ('acidente_trab', models.BooleanField(verbose_name='Acidente de trabalho')),
                ('trazido', models.CharField(choices=[('CP', 'Condução Própria'), ('AM', 'Ambulância'), ('SB', 'Samu/Bombeiro'), ('PV', 'Policiais e Viaturas')], max_length=1, verbose_name='Trazido por')),
                ('acompanhante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acompanhante')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa da Viatura')),
                ('pressao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pressão Arterial')),
                ('temperatura', models.IntegerField(blank=True, null=True, verbose_name='Temperatura')),
                ('peso', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('altura', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('dextro', models.BooleanField(verbose_name='Dextro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('hipotese', models.TextField(blank=True, null=True, verbose_name='Hipótese Diagnostica')),
                ('conduta', models.TextField(blank=True, null=True, verbose_name='Condulta')),
                ('anotacoes', models.TextField(blank=True, null=True, verbose_name='Anotações')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('realizado', models.BooleanField(verbose_name='Concluido')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='core/static/arq')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exa_atende', to='core.Atendimento', verbose_name='Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('funcao', models.CharField(choices=[('M', 'Médico'), ('A', 'Atendente'), ('E', 'Enfermeiro'), ('F', 'Farmaceutico')], max_length=1, verbose_name='Função')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logomarca')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('num_end', models.IntegerField(verbose_name='Numero')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cnes', models.IntegerField(verbose_name='CNES')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_fun', to='core.Funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Laudo',
                'verbose_name_plural': 'Laudos',
                'ordering': ['paciente'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('quatidade', models.IntegerField(verbose_name='Quatidade')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('rg', models.IntegerField(blank=True, null=True, verbose_name='RG')),
                ('uf_nas', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pai')),
                ('mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mãe')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('telefone', models.IntegerField(blank=True, null=True, verbose_name='Contato')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('uf_end', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('ibge', models.IntegerField(blank=True, null=True, verbose_name='IBGE')),
                ('raca', models.CharField(choices=[('BA', 'Branca'), ('NE', 'Negro'), ('AM', 'Amarela'), ('PA', 'Parda'), ('IN', 'Indígena'), ('OU', 'Outra'), ('ND', 'Não Declarado')], max_length=2, verbose_name='Raça')),
                ('etnia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etnia')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.IntegerField(verbose_name='Procedimento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('cbo', models.IntegerField(blank=True, null=True, verbose_name='CBO')),
                ('cid', models.IntegerField(blank=True, null=True, verbose_name='CID')),
                ('carater_atend', models.IntegerField(blank=True, null=True, verbose_name='Carater Atendimento')),
                ('autorizacao', models.IntegerField(blank=True, null=True, verbose_name='Número Autorização')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_atende', to='core.Atendimento', verbose_name='Atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_par', to='core.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ate_fun', to='core.Funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ate_par', to='core.Paciente', verbose_name='Paciente'),
        ),
    ]
