# Generated by Django 2.1.7 on 2019-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190327_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='num_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
    ]
