# Generated by Django 2.1.7 on 2019-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190327_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('M', 'Médico'), ('A', 'Atendente'), ('E', 'Enfermeiro'), ('F', 'Farmaceutico'), ('S', 'Administrador')], max_length=1, verbose_name='Função'),
        ),
    ]
